  // This file is generated by Auto Local. Do not edit any things.
  import 'package:flutter/material.dart';
import 'package:flutter_locales2/flutter_locales2.dart';
  class Lang {

    static String get(BuildContext context,{required LangKey key}) {
    return Locales.string(context, key.key) ?? '';
  }
  }
      enum LangKey{
appS('app_s'),
letsCheckYourTasks('lets_check_your_tasks'),
welcomeBack('welcome_back');
  const LangKey(this.key);
  final String key;
 }



  