  // This file is generated by Auto Local. Do not edit any things.
  import 'package:flutter/material.dart';
import 'package:flutter_locales2/flutter_locales2.dart';
  class Lang {

    static String get(BuildContext context,{required LangKey key}) {
    return Locales.string(context, key.key) ?? '';
  }
  }
      enum LangKey{
add('add'),
addNote('add_note'),
addReminder('add_reminder'),
addTasks('add_tasks'),
all('all'),
am('am'),
appS('app_s'),
apr('apr'),
april('april'),
areYouSureDeleteTask('are_you_sure_delete_task'),
aug('aug'),
august('august'),
cancel('cancel'),
category('category'),
completed('completed'),
day('day'),
dec('dec'),
december('december'),
deleteTask('delete_task'),
deletingTask('deleting_task'),
done('done'),
error('error'),
feb('feb'),
february('february'),
finished('finished'),
fri('fri'),
friday('friday'),
hours('hours'),
inProgress('in_progress'),
jan('jan'),
january('january'),
jul('jul'),
july('july'),
jun('jun'),
june('june'),
letsCheckYourTasks('lets_check_your_tasks'),
mar('mar'),
march('march'),
may('may'),
minute('minute'),
mon('mon'),
monday('monday'),
no('no'),
noLecturesToday('no_lectures_today'),
notStartedYet('not_started_yet'),
nov('nov'),
november('november'),
oct('oct'),
october('october'),
ok('ok'),
optional('optional'),
pm('pm'),
remaining('remaining'),
remainingTime('remaining_time'),
sat('sat'),
saturday('saturday'),
sep('sep'),
september('september'),
sun('sun'),
sunday('sunday'),
taskDetails('task_details'),
taskExpirationDate('task_expiration_date'),
taskName('task_name'),
tasks('tasks'),
thu('thu'),
thursday('thursday'),
tue('tue'),
tuesday('tuesday'),
wed('wed'),
wednesday('wednesday'),
welcomeBack('welcome_back'),
yes('yes'),
yourLecturesToday('your_lectures_today'),
yourTasks('your_tasks');
  const LangKey(this.key);
  final String key;
 }



  