// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDSVtkViLMkQCsqdb09geH2Pij5CZ-BVig',
//     appId: '1:262060048933:web:58ef7c44fe732ffabab5cc',
//     messagingSenderId: '262060048933',
//     projectId: 'khlfan-shtayn',
//     authDomain: 'khlfan-shtayn.firebaseapp.com',
//     storageBucket: 'khlfan-shtayn.appspot.com',
//     measurementId: 'G-5RZHKK3YQR',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAh_3NMIPz0vHowNrWNK6Vm0cz0J2zdWQk',
//     appId: '1:262060048933:android:0c02fa07cf1e7354bab5cc',
//     messagingSenderId: '262060048933',
//     projectId: 'khlfan-shtayn',
//     storageBucket: 'khlfan-shtayn.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAvmeiw3u1FSeZ3xNg5qPyaG4jwSHrfLkU',
//     appId: '1:262060048933:ios:177790a23674377cbab5cc',
//     messagingSenderId: '262060048933',
//     projectId: 'khlfan-shtayn',
//     storageBucket: 'khlfan-shtayn.appspot.com',
//     iosBundleId: 'com.khlfanshtayn.abom',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAvmeiw3u1FSeZ3xNg5qPyaG4jwSHrfLkU',
//     appId: '1:262060048933:ios:896427c2d16e1940bab5cc',
//     messagingSenderId: '262060048933',
//     projectId: 'khlfan-shtayn',
//     storageBucket: 'khlfan-shtayn.appspot.com',
//     iosBundleId: 'com.khlfan.shtain.abom.khlfanShtain.RunnerTests',
//   );
// }
