


List<Map<String,dynamic>> dayMsgs=[
  {"ar":"الإصرار هو المفتاح لتحقيق الأحلام. 🌟","en":"Determination is the key to achieving dreams. 🌟"},
  {"ar":"النجاح ليس محظوظاً، إنه نتاج عمل مستمر ومثابرة. 💪","en":"Success is not luck; it's the result of continuous effort and perseverance. 💪"},
  {"ar":"كل يوم هو فرصة جديدة للبداية. 🌅","en":"Every day is a new opportunity for a fresh start. 🌅"},
  {"ar":"التفاؤل هو سلاح قوي ضد التحديات. 🌈","en":"Optimism is a powerful weapon against challenges. 🌈"},
  {"ar":"الابتسامة تكسب القلوب وتحطم الصعاب. 😊","en":"A smile wins hearts and breaks barriers. 😊"},
  {"ar":"الإبداع ينشأ من خلق الفرص. 🚀","en":"Creativity arises from creating opportunities. 🚀"},
  {"ar":"التعلم مستمر، والنمو لا يتوقف. 📚","en":"Learning is continuous, and growth never stops. 📚"},
  {"ar":"استمتع بالرحلة ولا تتسرع في الوصول. 🌺","en":"Enjoy the journey and don't rush to the destination. 🌺"},
  {"ar":"الثقة بالنفس هي المفتاح لفتح أبواب الفرص. 🔑","en":"Self-confidence is the key to unlocking doors of opportunities. 🔑"},
  {"ar":"الصبر يجني ثماره في اللحظات الصعبة. ⌛","en":"Patience bears fruit in challenging moments. ⌛"},
  {"ar":"ابدأ بالقليل، وابنِ تدريجياً. 🌱","en":"Start small and build gradually. 🌱"},
  {"ar":"التفاؤل يخلق طاقة إيجابية. +","en":"Optimism creates positive energy. +"},
  {"ar":"لا تخشى الفشل، بل استفد منه. 🔄","en":"Don't fear failure; learn from it. 🔄"},
  {"ar":"كن رائعًا في عالم مليء بالروتين. 🌟","en":"Be extraordinary in a world full of routine. 🌟"},
  {"ar":"العمل الجماعي يحقق الإنجازات الكبيرة. 🤝","en":"Teamwork achieves great accomplishments. 🤝"},
  {"ar":"استمتع باللحظة، فالحاضر هو هدية. 🎁","en":"Enjoy the moment, for the present is a gift. 🎁"},
  {"ar":"اجعل الفشل درسًا لا تكراره. 🚫","en":"Turn failure into a lesson not to be repeated. 🚫"},
  {"ar":"التحديات تجعلنا أقوى وأذكى. 🧠","en":"Challenges make us stronger and smarter. 🧠"},
  {"ar":"النجاح يحتاج إلى تخطيط وتنفيذ. 📊","en":"Success requires planning and execution. 📊"},
  {"ar":"لا تقارن نفسك بالآخرين، كن فريدًا. 🌈","en":"Don't compare yourself to others; be unique. 🌈"},
  {"ar":"الحياة قصيرة، استمتع بكل لحظة. ⏳","en":"Life is short, enjoy every moment. ⏳"},
  {"ar":"اعمل بجد واستمتع بما تفعل. 🚀","en":"Work hard and enjoy what you do. 🚀"},
  {"ar":"التحدي يجعل النجاح أكثر قيمة. 💎","en":"Challenge makes success more valuable. 💎"},
  {"ar":"الإيمان بالنفس هو بداية كل إنجاز. 🌟","en":"Believing in yourself is the beginning of every achievement. 🌟"},
  {"ar":"احتفل بالتقدم الصغير والكبير. 🎉","en":"Celebrate both small and big progress. 🎉"},
  {"ar":"الابتكار يعزز التطور والنجاح. 💡","en":"Innovation enhances progress and success. 💡"},
  {"ar":"الصداقات تبني جسوراً نحو النجاح. 🤝","en":"Friendships build bridges towards success. 🤝"},
  {"ar":"كن ذا أثر إيجابي في حياة الآخرين. +","en":"Make a positive impact in the lives of others. +"},
  {"ar":"العزيمة تحقق المستحيل. 🌌","en":"Determination achieves the impossible. 🌌"},
  {"ar":"استمر في التعلم وتطوير نفسك. 📚","en":"Keep learning and developing yourself. 📚"},
  {"ar":"كن كالشمس وأشرق حتى في الأيام الغائمة. ☀️","en":"Be like the sun and shine even on cloudy days. ☀️"},
  {"ar":"الإبداع يولد من التفكير خارج الصندوق. 📦","en":"Creativity is born from thinking outside the box. 📦"},
  {"ar":"الصبر هو المفتاح إلى حقل الزهور. 🌷","en":"Patience is the key to the field of flowers. 🌷"},
  {"ar":"كن ممتنًا لكل تجربة تعلمت منها. 🙏","en":"Be grateful for every experience you've learned from. 🙏"},
  {"ar":"توقع الأفضل واستعد للأسوأ. 🌈","en":"Expect the best and prepare for the worst. 🌈"},
  {"ar":"التفكير الإيجابي يخلق واقعًا إيجابيًا. +","en":"Positive thinking creates a positive reality. +"},
  {"ar":"لا تيأس أبدًا، فالفجر يأتي بعد الليل. 🌅","en":"Never lose hope; dawn comes after the night. 🌅"},
  {"ar":"ابنِ جسرًا إلى أحلامك بالعمل الجاد. 🌉","en":"Build a bridge to your dreams through hard work. 🌉"},
  {"ar":"كل يوم هو فرصة لتحسين نفسك. 🌟","en":"Every day is a chance to improve yourself. 🌟"},
  {"ar":"تخلص من الشكوى وابدأ بالعمل. 🚀","en":"Get rid of complaints and start working. 🚀"},
  {"ar":"التحديات تجعل الحياة أكثر إثارة. 🎢","en":"Challenges make life more thrilling. 🎢"},
  {"ar":"الإبداع يولد من الشغف والتفرد. 🔥","en":"Creativity arises from passion and uniqueness. 🔥"},
  {"ar":"الثقة هي سر تحقيق الأهداف الكبيرة. 🔒","en":"Confidence is the secret to achieving big goals. 🔒"},
  {"ar":"التغيير هو فرصة للنمو والتحسين. 🔄","en":"Change is an opportunity for growth and improvement. 🔄"},
  {"ar":"الصدق مع الذات يبني النجاح الدائم. 💬","en":"Honesty with oneself builds lasting success. 💬"},
  {"ar":"كن فعّالاً، لا مجرد موجود. 🚀","en":"Be effective, not just present. 🚀"},
  {"ar":"الأحلام تأتي صحيحة للمتحملين. 🌌","en":"Dreams come true for the persistent. 🌌"},
  {"ar":"العمل بذكاء يضاعف النتائج. 🧠","en":"Working smart multiplies the results. 🧠"},
  {"ar":"تحدى النفس لتكون أفضل يومًا بعد يوم. 🌟","en":"Challenge yourself to be better day by day. 🌟"},
  {"ar":"الإبداع يبني جسوراً للعالم الجديد. 🌉","en":"Creativity builds bridges to the new world. 🌉"},
  {"ar":"الحياة مليئة بالفرص، اعتنقها. 🌍","en":"Life is full of opportunities; embrace them. 🌍"},
  {"ar":"التواصل الجيد يفتح أبواب التفاهم. 🗣️","en":"Good communication opens doors to understanding. 🗣️"},
  {"ar":"كن قوياً في وجه الضغوط والتحديات. 💪","en":"Be strong in the face of pressures and challenges. 💪"},
  {"ar":"الابتسامة تعكس جمال الروح. 😇","en":"A smile reflects the beauty of the soul. 😇"},
  {"ar":"التفكير الإيجابي يحقق الطموحات. +","en":"Positive thinking achieves aspirations. +"},
  {"ar":"النجاح يأتي للذين يعملون بكل قلبهم. ❤️","en":"Success comes to those who work with all their hearts. ❤️"},
  {"ar":"كن نوراً في عالم مظلم. 💡","en":"Be a light in a dark world. 💡"},
  {"ar":"احترم وقتك وقدرتك على التأثير. ⌛","en":"Respect your time and your ability to make an impact. ⌛"},
  {"ar":"اجعل الفشل درجة نجاح جديدة. 📈","en":"Turn failure into a new level of success. 📈"},
  {"ar":"التعلم المستمر يحقق الريادة. 🚀","en":"Continuous learning achieves leadership. 🚀"},
  {"ar":"كن محفزاً للآخرين وساعد في النمو. 🌱","en":"Be a motivator for others and help in their growth. 🌱"},
  {"ar":"المرونة هي مفتاح التكيف والتفوق. 🌐","en":"Flexibility is the key to adaptation and excellence. 🌐"},
  {"ar":"ابنِ الجسور ولا تقيد نفسك. 🌉","en":"Build bridges and don't limit yourself. 🌉"},
  {"ar":"كن جامحاً في تحقيق أحلامك. 🚀","en":"Be bold in pursuing your dreams. 🚀"},
  {"ar":"التحفيز يأتي من الداخل ويشع إلى الخارج. ✨","en":"Motivation comes from within and radiates outward. ✨"},
  {"ar":"الأفكار الإيجابية تخلق حياة إيجابية. +","en":"Positive thoughts create a positive life. +"},
  {"ar":"تواصل مع الآخرين بحب وتقدير. ❤️","en":"Connect with others with love and appreciation. ❤️"},
  {"ar":"استمتع بالتحديات لأنها تشكل نمواً. 🌱","en":"Enjoy challenges as they constitute growth. 🌱"},
  {"ar":"كن شخصاً محترماً وكريماً في تعاملك. 🤝","en":"Be a respectful and kind person in your interactions. 🤝"},
  {"ar":"العمل الجماعي يحقق الإنجازات الكبيرة. 🤝","en":"Collaboration achieves great accomplishments. 🤝"},
  {"ar":"ابتعد عن السلبية وانغمس في الإيجابية. +","en":"Stay away from negativity and immerse yourself in positivity. +"},
  {"ar":"المرونة هي مفتاح النجاح في عصر التغيير. 🔄","en":"Flexibility is the key to success in the age of change. 🔄"},
  {"ar":"احتفظ بروح الطفولة والفضول. 🧒","en":"Keep the spirit of childhood and curiosity. 🧒"},
  {"ar":"التحدي يكسر الروتين ويفتح آفاقاً جديدة. 🌅","en":"Challenge breaks routine and opens new horizons. 🌅"},
  {"ar":"كن صادقاً مع نفسك ومع الآخرين. 💬","en":"Be honest with yourself and with others. 💬"},
  {"ar":"الابتسامة تعكس السعادة الداخلية. 😊","en":"A smile reflects inner happiness. 😊"},
  {"ar":"استمتع بكل تجربة واستفد منها. 🌟","en":"Enjoy every experience and learn from it. 🌟"},
  {"ar":"التفاؤل هو مفتاح النجاح الدائم. 🌈","en":"Optimism is the key to lasting success. 🌈"},
  {"ar":"كن ممتنًا للفرص والتحديات على حد سواء. 🙏","en":"Be grateful for both opportunities and challenges. 🙏"},
  {"ar":"الحياة مثل لعبة، استمتع باللعبة. 🎮","en":"Life is like a game; enjoy playing it. 🎮"},
  {"ar":"استثمر وقتك في ما يعزز نموك الشخصي. ⏳","en":"Invest your time in what enhances your personal growth. ⏳"},
  {"ar":"العزيمة تحول الأحلام إلى حقيقة. 💭","en":"Determination turns dreams into reality. 💭"},
  {"ar":"كن ذا هدف وتوجه نحوه. 🎯","en":"Have a goal and move towards it. 🎯"},
  {"ar":"اجعل التغيير صديقًا لا عدوًا. 🔄","en":"Make change a friend, not an enemy. 🔄"},
  {"ar":"التفاؤل يصنع مستقبلًا مشرقًا. 🌅","en":"Optimism creates a bright future. 🌅"},
  {"ar":"النجاح يبدأ بخطوة واحدة صغيرة. 👣","en":"Success starts with one small step. 👣"},
  {"ar":"ابنِ روابط قوية مع الآخرين. 🤝","en":"Build strong connections with others. 🤝"},
  {"ar":"كن جامعًا للخبرات والتجارب. 🧠","en":"Be a collector of experiences and experiments. 🧠"},
  {"ar":"تحدى نفسك لتحقيق إمكانياتك الكاملة. 💪","en":"Challenge yourself to reach your full potential. 💪"},
  {"ar":"كن ملهمًا للآخرين وشارك بالإيجابية. 🌟","en":"Be an inspiration to others and share positivity. 🌟"},
  {"ar":"الابتسامة تكسر الجدران وتبني جسوراً. 😊","en":"A smile breaks walls and builds bridges. 😊"},
  {"ar":"تحديات الحياة تصقل الروح والشخصية. 🔧","en":"Life's challenges refine the soul and character. 🔧"},
  {"ar":"العمل بجد يجعل الأحلام حقيقة. 🌌","en":"Working hard makes dreams a reality. 🌌"},
  {"ar":"الأفكار الإيجابية تثمر نتائج إيجابية. +","en":"Positive thoughts yield positive results. +"},
  {"ar":"استثمر في نموك الشخصي كما تستثمر في المال. 💹","en":"Invest in your personal growth as you invest in money. 💹"},
  {"ar":"كن قوياً حتى يعجز الحياة عن هزيمتك. 💪","en":"Be strong until life is unable to defeat you. 💪"},
  {"ar":"التعاون يعزز الإنجازات ويفتح آفاقاً جديدة. 🤝","en":"Collaboration enhances achievements and opens new horizons. 🤝"},
  {"ar":"ابتسم حتى وإن كنت تمر بلحظات صعبة. 😊","en":"Smile even if you're going through tough times. 😊"},
  {"ar":"التحدي يعزز القوة والصمود. 💪","en":"Challenge enhances strength and resilience. 💪"},
  {"ar":"كن مثابراً، فالنجاح يحتاج إلى وقت. 🕰️","en":"Be persistent, for success takes time. 🕰️"},
  {"ar":"التفكير الإيجابي يحقق الأحلام. 🌟","en":"Positive thinking achieves dreams. 🌟"},
  {"ar":"التحدي يجعل الحياة أكثر إثارة. 🎢","en":"Challenge makes life more thrilling. 🎢"},
  {"ar":"التفاؤل يصنع مستقبلًا مشرقًا. 🌅","en":"Optimism creates a bright future. 🌅"},
  {"ar":"النجاح يبدأ بخطوة واحدة صغيرة. 👣","en":"Success starts with one small step. 👣"},
  {"ar":"ابنِ روابط قوية مع الآخرين. 🤝","en":"Build strong connections with others. 🤝"},
  {"ar":"كن جامعًا للخبرات والتجارب. 🧠","en":"Be a collector of experiences and experiments. 🧠"},
  {"ar":"تحدى نفسك لتحقيق إمكانياتك الكاملة. 💪","en":"Challenge yourself to reach your full potential. 💪"},
  {"ar":"كن ملهمًا للآخرين وشارك بالإيجابية. 🌟","en":"Be an inspiration to others and share positivity. 🌟"},
  {"ar":"الابتسامة تكسر الجدران وتبني جسوراً. 😊","en":"A smile breaks walls and builds bridges. 😊"},
  {"ar":"تحديات الحياة تصقل الروح والشخصية. 🔧","en":"Life's challenges refine the soul and character. 🔧"},
  {"ar":"العمل بجد يجعل الأحلام حقيقة. 🌌","en":"Working hard makes dreams a reality. 🌌"},
  {"ar":"الأفكار الإيجابية تثمر نتائج إيجابية. +","en":"Positive thoughts yield positive results. +"},
  {"ar":"استثمر في نموك الشخصي كما تستثمر في المال. 💹","en":"Invest in your personal growth as you invest in money. 💹"},
  {"ar":"كن قوياً حتى يعجز الحياة عن هزيمتك. 💪","en":"Be strong until life is unable to defeat you. 💪"},
  {"ar":"التعاون يعزز الإنجازات ويفتح آفاقاً جديدة. 🤝","en":"Collaboration enhances achievements and opens new horizons. 🤝"},
  {"ar":"ابتسم حتى وإن كنت تمر بلحظات صعبة. 😊","en":"Smile even if you're going through tough times. 😊"},
  {"ar":"التحدي يعزز القوة والصمود. 💪","en":"Challenge enhances strength and resilience. 💪"},
  {"ar":"كن مثابراً، فالنجاح يحتاج إلى وقت. 🕰️","en":"Be persistent, for success takes time. 🕰️"},
  {"ar":"التفكير الإيجابي يحقق الأحلام. 🌟","en":"Positive thinking achieves dreams. 🌟"},
  {"ar":"التحدي يجعل الحياة أكثر إثارة. 🎢","en":"Challenge makes life more thrilling. 🎢"},
  {"ar":"التفاؤل يصنع مستقبلًا مشرقًا. 🌅","en":"Optimism creates a bright future. 🌅"},

];



final List<String> avatars=[
  "i1.png",
  "i2.png",
  "i3.png",
  "i4.png",
  "i5.png",
  "i6.png",
  "i7.png",
  "i8.png",
  "i9.png",
  "i10.png",
  "i11.png",
  "i12.png",
  "i13.png",
  "i14.png",
  "i15.png",
  "i16.png",
  "i17.png",
  "i18.png",
  "i19.png",
  "i20.png",
  "i21.png",
  "i22.png",
  "i23.png",
  "i24.png",
  "i25.png",
  "i26.png",
  "i27.png",
  "i28.png",
  "i29.png",
  "i30.png",
  "i31.png",
  "i32.png",
  "i33.png",
  "i34.png",
  "i35.png",
  "i36.png",
  "i37.png",
  "i38.png",
  "i39.png",
  "i40.png",
  "i41.png",
  "i42.png",
  "i43.png",
  "i44.png",
  "i45.png",
  "i46.png",

  "i47.png",
  "i48.png",
  "i49.png",
  "i50.png",
  "i51.png",
  "i52.png",
  "i53.png",
  "i54.png",
  "i55.png",
  "i56.png",
  "i57.png",
  "i58.png",
  "i59.png",
  "i60.png",
  "i61.png",
  "i62.png",
  "i63.png",
  "i64.png",
  "i65.png",
  "i66.png",
  "i67.png",
  "i68.png",
  "i69.png",
  "i70.png",
  "i71.png",
  "i72.png",
  "i73.png",
  "i74.png",
  "i75.png",
  "i76.png",
  "i77.png",
  "i78.png",
  "i79.png",
  "i80.png",
  "i81.png",
  "i82.png",
  "i83.png",
  "i84.png",
  "i85.png",
  "i86.png",
  "i87.png",
  "i88.png",
  "i89.png",
  "i90.png",
  "i91.png",
  "i92.png",
  "i93.png",
];